#version: "3"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../app/public:/app/public
  app:
    build: services/php
    volumes:
      - ../app/public:/app/public
  db:
    image: mariadb:latest
    env_file: ../.env
    #environment:
    #  MYSQL_ROOT_PASSWORD: "root"
    #  MYSQL_DATABASE: "cv_db"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}
